---
apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: sql-app-as-a-service
  namespace: default
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: sqlapps.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: sqlapp
        plural: sqlapps
        singular: sqlapp
      scope: Namespaced
      versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    env:
                      default: staging
                      description: |
                        Evironment to schedule deployment to. Staging or Prod
                      enum:
                        - staging
                        - prod
                      type: string
                    image:
                      description: |
                        Image to deploy
                      type: string
                  type: object
                  required:
                    - env
                    - image
              type: object
          served: true
          storage: true
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: create-sql
            namespace: default
          spec:
            containers:
              - image: docker.io/abangser/stage1-pipeline:v0.1.0
                name: sqlapp-configure-stage1-pipeline
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: create-deployment-using-sql
            namespace: default
          spec:
            containers:
              - image: docker.io/abangser/stage2-pipeline:v0.1.0
                name: sqlapp-configure-stage2-pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sql-app-as-a-service-resource-pipeline-credentials
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sql-app-as-a-service-resource-pipeline-credentials
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sql-app-as-a-service-resource-pipeline-credentials
subjects:
  - kind: ServiceAccount
    name: sql-app-as-a-service-resource-pipeline
    namespace: default
