---
apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: sql-app-as-a-service
  namespace: default
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: sqlapp.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: sqlapp
        plural: sqlapp
        singular: sqlapp
      scope: Namespaced
      versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    env:
                      default: staging
                      description: |
                        Evironment to schedule deployment to. Staging or Prod
                      enum:
                      - staging
                      - prod
                      type: string
                    image:
                      description: |
                        Image to deploy
                      type: string
                    replicas:
                      default: 1
                      description: |
                        Replicas for the deployment
                      type: integer
                  type: object
              type: object
          served: true
          storage: true
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: create-sql
            namespace: default
          spec:
            containers:
              - image: ghcr.io/vfarcic/london-2024/create-sql-app-as-a-service-configure-pipeline:v0.1.0
                name: sqlapp-configure-pipeline
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: create-deployment-using-sql
            namespace: default
          spec:
            containers:
              - image: ghcr.io/vfarcic/london-2024/create-deployment-sql-app-as-a-service-configure-pipeline:v0.1.0
                name: sqlapp-configure-pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sql-app-as-a-service-resource-pipeline-credentials
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sql-app-as-a-service-resource-pipeline-credentials
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sql-app-as-a-service-resource-pipeline-credentials
subjects:
- kind: ServiceAccount
  name: sql-app-as-a-service-resource-pipeline
  namespace: default
