---
apiVersion: v1
data:
  password: cG9zdGdyZXM=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: silly-demo
  name: silly-demo-password
---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  labels:
    app.kubernetes.io/name: silly-demo
  name: silly-demo
spec:
  compositionSelector:
    matchLabels:
      db: postgresql
      provider: aws
  id: silly-demo
  parameters:
    size: small
    version: "13"
