---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: my-vm
spec:
  forProvider:
    ami: ami-052efd3df9dad4825
    region: us-west-2
    instanceType: t2.nano
    subnetIdRef:
      name: my-vm
    tags:
      Name: my-vm
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: InstanceState
metadata:
  name: my-vm
spec:
  forProvider:
    region: us-west-2
    instanceIdRef:
      name: my-vm
    state: running
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: my-vm
spec:
  forProvider:
    region: us-west-2
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: my-vm
spec:
  forProvider:
    region: us-west-2
    availabilityZone: us-west-2a
    cidrBlock: 10.0.0.0/24
    vpcIdRef:
      name: my-vm
    mapPublicIpOnLaunch: true
